# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.IntegerField(default=0, verbose_name='Tipo de Emeg\xeancia')),
                ('latitude', models.CharField(max_length=11, verbose_name='Latitude')),
                ('logitude', models.CharField(max_length=11, verbose_name='Longitude')),
                ('time_log', models.DateTimeField(verbose_name='Hor\xe1rio e cadastro')),
                ('time_out', models.DateTimeField(verbose_name='Hor\xe1rio de recebimento')),
                ('time_in', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
